# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PSz70Izp815jhVlmDOooU5Q2ktXSpZ0z
"""

import numpy as np

my_lst=[1,2,3,4,5]
arr=np.array(my_lst)

type(arr)

arr

arr.shape

my_lst1=[1,2,3,4,5]
my_lst2=[3,4,5,6,7]
my_lst3=[5,6,7,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

arr

arr.shape

arr.reshape(5,3)

arr.shape



"""Indexing"""

arr[:,:]

arr[:,3:]

arr

arr[0:2,0:2]

arr[1:,3:]

